import {useT} from "../../hooks/useT.ts";

export function useAdminSettingsText(pageLocale: string) {
    return {
        titleText: useT("dashboard.link.admin_settings", undefined, "Admin settings", pageLocale),
        aiKeysText: useT("admin.settings.ai_keys", undefined, "AI API keys", pageLocale),
        openAiKeyText: useT("admin.settings.openai_api_key", undefined, "OpenAI API key", pageLocale),
        deepSeekKeyText: useT("admin.settings.deepseek_api_key", undefined, "DeepSeek API key", pageLocale),
        siteLogoText: useT("admin.settings.site_logo", undefined, "Site logo", pageLocale),
        backgroundImageText: useT("admin.settings.background_image", undefined, "Background image", pageLocale),
        saveText: useT("admin.settings.save", undefined, "Save settings", pageLocale),
        savingText: useT("admin.settings.saving", undefined, "Saving...", pageLocale),
        updatedText: useT("admin.settings.updated", undefined, "Settings updated.", pageLocale),
        loadingText: useT("admin.settings.loading", undefined, "Loading admin settings...", pageLocale),
        siteLogoPreviewAltText: useT(
            "admin.settings.site_logo_preview",
            undefined,
            "Site logo preview",
            pageLocale,
        ),
        backgroundPreviewAltText: useT(
            "admin.settings.background_image_preview",
            undefined,
            "Background image preview",
            pageLocale,
        ),
        translationWarningMissingKeysText: useT(
            "admin.settings.translation_warning_missing_keys",
            undefined,
            "Automatic translations require at least one provider key (OpenAI or DeepSeek).",
            pageLocale,
        ),
        translationWarningAutoText: useT(
            "admin.settings.translation_warning_auto",
            undefined,
            "When API keys are provided, new locales are translated automatically on first encounter. If OpenAI is unavailable, DeepSeek is used when configured.",
            pageLocale,
        ),
        emailSettingsTitleText: useT("admin.email.settings.title", undefined, "Email settings", pageLocale),
        emailEnabledStatusText: useT(
            "admin.email.settings.status.enabled",
            undefined,
            "Email verification is enabled for self-registered users.",
            pageLocale,
        ),
        emailDisabledStatusText: useT(
            "admin.email.settings.status.disabled",
            undefined,
            "Email is not configured. Self-registered users can log in without verification.",
            pageLocale,
        ),
        smtpHostText: useT("admin.email.settings.smtp_host", undefined, "SMTP host", pageLocale),
        smtpPortText: useT("admin.email.settings.smtp_port", undefined, "SMTP port", pageLocale),
        smtpUsernameText: useT("admin.email.settings.smtp_username", undefined, "SMTP username", pageLocale),
        smtpPasswordText: useT("admin.email.settings.smtp_password", undefined, "SMTP password", pageLocale),
        smtpFromEmailText: useT("admin.email.settings.smtp_from_email", undefined, "SMTP from email", pageLocale),
        smtpUseStartTlsText: useT("admin.email.settings.smtp_use_starttls", undefined, "Use STARTTLS", pageLocale),
        authFrontendBaseUrlText: useT(
            "admin.auth.base_url.frontend",
            undefined,
            "Frontend base URL",
            pageLocale,
        ),
        authBackendBaseUrlText: useT(
            "admin.auth.base_url.backend",
            undefined,
            "Backend base URL",
            pageLocale,
        ),
        authBaseUrlsTitleText: useT(
            "setup.auth.base_urls",
            undefined,
            "Authentication base URLs",
            pageLocale,
        ),
        authBaseUrlsHintText: useT(
            "setup.auth.base_urls_hint",
            undefined,
            "Used in verification and reset links sent by email.",
            pageLocale,
        ),
        checkEmailSettingsText: useT("admin.email.settings.check", undefined, "Check email settings", pageLocale),
        checkingEmailSettingsText: useT("admin.email.settings.checking", undefined, "Checking...", pageLocale),
        emailSettingsCheckFailedText: useT(
            "admin.email.settings.check_failed",
            undefined,
            "Email settings check failed",
            pageLocale,
        ),
        loadFailedText: useT("admin.settings.load_failed", undefined, "Failed to load admin settings", pageLocale),
        saveFailedText: useT("admin.settings.save_failed", undefined, "Failed to save admin settings", pageLocale),
        siteNameText: useT("setup.field.site_name", undefined, "Site name", pageLocale),
        supportedLocalesText: useT("setup.field.supported_locales", undefined, "Supported locales", pageLocale),
        supportedLocalesHintText: useT(
            "setup.hint.supported_locales",
            undefined,
            "Comma-separated locale codes.",
            pageLocale,
        ),
        adminEmailText: useT("setup.field.admin_email", undefined, "Admin email", pageLocale),
        adminPasswordText: useT("setup.field.admin_password", undefined, "Admin password", pageLocale),
    };
}
